config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  # get "home/index"  #will work on localhost:3000/home/index

  # This sets the **root URL ("/")** of your application to point to the `index` action inside the `HomeController`.
  # So when someone visits `localhost:3000/`, Rails will look for the method `def index` in `app/controllers/home_controller.rb`
  # and render the corresponding view file `app/views/home/index.html.erb`.
  # root "home#index"  # Will work on localhost:3000/

  root "friends#index"  # Will work on localhost:3000/

  # This defines a custom GET route for the URL `/home/about`.
  # When a user visits `localhost:3000/home/about`, Rails will look for the method `def about` in `HomeController`,
  # and render the view `app/views/home/about.html.erb` (if it exists).
  get "home/about"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  # only allow them index and show methods (& pages) if the user is not authenticated
  before_action :authenticate_user!, except: [ :index, :show ]

  # before edit, update or destroying, check if its the correct user
  before_action :correct_user, only: [ :edit, :update, :destroy ]


  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_path, status: :see_other, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])

    redirect_to friends_path, notice: "Not authorized to edit this friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.expect(friend: [ :first_name, :last_name, :email, :phone, :twitter, :user_id ])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # for index.html.erb
  def index
  end

  # for about.html.erb
  def about
    # this is an instance variable with @ in front, will work everywhere on the respective page for that method(like this one is for about page)
    @about_me = "My name is Joker!"
    # refer about.html.erb

    @answer = 2+2

    # this is a local variable - will work only in this function
    # about_me = "Hello world"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>

    </div>
  <% end %>

  <div class="mb-3">
    <% form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="mb-3">
    <% form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="mb-3">
    <% form.label :email, style: "display: block" %>
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="mb-3">
    <% form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone" %>
  </div>

  <div class="mb-3">
    <% form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter" %>
  </div>

  <div>
    <% form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>
  
  <%# from devise gem %>
  <% current_user %>
  <% current_user.inspect %>

  <br/>
  <div>
    <%# giving nil as first arg, as this form is used for both create and update pages. %>
    <%= form.submit nil, class: "btn btn-primary" %>
  </div>  
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <td>
    <%# <strong>First name:</strong> %>
    <%= link_to friend.first_name + ' ' + friend.last_name, friend %>
    <% friend.first_name %> <% friend.last_name %>
  </td>

  <td>
    <%# <strong>Email:</strong> %>
    <%= friend.email %>
  </td>

  <td>
    <%# <strong>phone:</strong> %>
    <%= friend.phone %>
  </td>

  <td>
    <%# <strong>Twitter:</strong> %>
    <%= friend.twitter %>
  </td>



</div>

app/views/friends/edit.html.erb
<% content_for :title, "Editing friend" %>

<div class="card">
  <div class="card-header">
    <div class="d-flex justify-content-between align-items-center">
      <h1>Editing friend</h1>

        <div class="d-flex gap-2 ">
        <%= link_to "Show this friend", @friend, class:"btn btn-secondary" %> 
        <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
      </div>
    </div>
  </div>

  <div class="card-body">
    <%= render "form", friend: @friend %>
  </div>
</div>

app/views/friends/index.html.erb
<!-- <p style="color: green"><%= notice %> </p> -->  
<%# _alerts.html.erb added %>


<% if user_signed_in? %>

  <% content_for :title, "Friends" %>

    <div class="card">
      <div class="card-header bg-dark-subtle">
        <h1>Friends</h1>
      </div>

      <div class="card-body bg-secondary-subtle">
        <div id="friends">

          <table class="table table-striped table-bordered table-hover text-center">

          <thead class="thead-dark">
            <tr>
              <th>Name</th>
              <%# <th>Last name</th> %>
              <th>Email</th>
              <th>Phone</th>
              <th>Twitter</th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @friends.each do |friend| %>
              <% if friend.user == current_user %>
              <tr><%= render friend %>
                <td>
                  <%= link_to "Show this friend", friend, class:"btn btn-secondary" %>
                </td>
              </tr> 
              <% end %>
            <% end %>
          </tbody>

          </table>

          <%= link_to "New friend", new_friend_path, class:"btn btn-primary" %>
        </div>

      </div>
    </div>

<% else %>

  <h1> Hello world!</h1>
  <p> This is the home page. Cheers on Rails!!</p>

  <h1>Home#index</h1>
  <h1>Hello World</h1>
  <p>Find me in app/views/friends/index.html.erb</p>

<% end %>

app/views/friends/new.html.erb
<% content_for :title, "New friend" %>

<div class="card">
  <div class="card-header">
    <div class="d-flex justify-content-between align-items-center">
      <h1>Add New friend</h1>

      <div>
        <%= link_to "Existing Friends", friends_path, class:"btn btn-secondary" %>
      </div>
    </div> 
  </div>

  <div class="card-body">
    <%= render "form", friend: @friend %>
  </div>
</div>




<br/>

<br/>
<br/>

app/views/friends/show.html.erb
<!-- <p class="alert alert-warning alert-dismissible fade show" style="color: green"><%= notice %></p> --> 
<%# _alerts.html.erb added %>

  <table class="table table-striped table-bordered table-hover text-center">

    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <%# <th>Last name</th> %>
        <th>Email</th>
        <th>Phone</th>
        <th>Twitter</th>
      </tr>
    </thead>

    <tbody>
        <tr>
          <%= render @friend %>
        </tr>
    </tbody>
  </table>
  
  <div class="d-flex gap-2">
    <%= link_to "Edit", edit_friend_path(@friend), class: "btn btn-secondary" %>
    <%= link_to "Back", friends_path, class: "btn btn-secondary" %>
    <%= button_to "Delete Friend", @friend, method: :delete, class: "btn btn-danger", form: { class: "m-0" } %>
  </div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">


    <%# 'Friend Project is the visible content, root_path is where the click on content goes' %>
    <%= link_to 'Friends Project', root_path, class:"navbar-brand" %>
    <%# instead of the below, we use the above link_to %>
    <%# <a class="navbar-brand" href="#">Friend Project</a> %>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">

          <%# path is about inside home and we put _path at the last  %>
          <%= link_to 'About Us', home_about_path, class:"nav-link" %>
          <%# <a class="nav-link" href="#">Link</a> %>
        </li>

        <% if user_signed_in? %>          
          <li>
              <%= link_to 'Add Friends', new_friend_path, class:"nav-link" %>
          </li>

          <li> 
            <%# destroy user session will only work for DELETE method %>
            <%# not working with link_to, needs ujs for it to send delete request in that case. was sending GET without ujs and with link_to %>
            <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link btn btn-link' %>
          </li>

          <li>
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
          </li>
        <% else %>
          
          <li>
              <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
          </li>

          <li>
            <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>

      </ul>

      <!--<form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> -->
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1> About us </h1> 
<hr>

<h3> Friends Project </h3>

<p> 
    <%# refer home_controller - using an instance variable %>
    
    Using instance variable from the controller:
    <%= @about_me %>
    <%= @answer %>
</p>

<p> 
    <% answer = 2+3 %>
    Adding 2 and 3 using ruby inside erb file : <%= answer %>
</p>

<ul>
    <li>Add and maintain Friends list</li>
    <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo sint voluptate eos fugit illo, magnam eveniet necessitatibus alias voluptates laborum amet beatae molestias itaque commodi debitis architecto, excepturi vitae a!</li>
    <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo sint voluptate eos fugit illo, magnam eveniet necessitatibus alias voluptates laborum amet beatae molestias itaque commodi debitis architecto, excepturi vitae a!</li>
</ul>

app/views/home/index.html.erb
<h1>Home#index</h1>
<h1>Hello World</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" >
    <%= notice %> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Friends Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">


  </head>


<%# Rest of the contents except for the yeild stay the same. for example nav bars can be added here, and no need to import them in each of the html file %>
  <body>
    <%# Header here....<br /><br /> %>

    <%# because of render, it knows the file is _header.html.erb in place of header %>
    <%= render 'home/header' %>


    <div class="container">

      
      <br />
      <% if notice %>
        <%= render 'layouts/alerts'%>
      <%end%>

      <br />
      <%# yield is the place where the code from other html files go in %>
      <%= yield %>
    </div>

    <%# <br /> Footer here... %>
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.min.js" integrity="sha384-RuyvpeZCxMJCqVUGFI0Do1mQrods/hhxYlcVfGPOfQtPJh0JCw12tUAZ/Mv10S7D" crossorigin="anonymous"></script>

  </body>
</html>